import type { DayPlan, TripSession } from './types'

export function formatItineraryMarkdown(plans: DayPlan[], session?: TripSession) {
  const title = session?.title || '东京 6 日轻松自由行'
  const summary = session?.summary || '专为第一次去东京的用户设计，减少跨区移动，保留充足的探索空间。'
  const lines = [
    `# ${title}`,
    '',
    summary,
    '',
    '## 每日行程',
    '',
  ]

  for (const plan of plans) {
    lines.push(`### Day ${plan.day} · ${plan.title}`)
    lines.push('')
    lines.push(`- 主题：${plan.theme}`)
    lines.push(`- 强度：${plan.intensity}`)
    lines.push(`- 预计交通：${plan.estimatedTransport}`)
    lines.push(`- 规划理由：${plan.reason}`)
    lines.push('')

    for (const slot of plan.slots) {
      lines.push(`#### ${slot.period}`)
      for (const activity of slot.activities) {
        lines.push(`- ${activity}`)
      }
      lines.push('')
    }

    lines.push(`地点顺序：${plan.places.map(place => place.name).join(' -> ')}`)
    lines.push('')
  }

  lines.push('---')
  lines.push('Generated by CoTrip AI')
  lines.push('')

  return lines.join('\n')
}

export function getDemoShareUrl(session?: TripSession) {
  const tripId = encodeURIComponent(session?.title || 'tokyo-6d-demo')
  const publicUrl = process.env.NEXT_PUBLIC_APP_URL

  if (publicUrl) {
    return `${publicUrl.replace(/\/$/, '')}/?trip=${tripId}`
  }

  if (typeof window !== 'undefined') {
    return `${window.location.origin}/?trip=${tripId}`
  }

  return `/?trip=${tripId}`
}

export async function writeClipboardText(text: string) {
  try {
    await navigator.clipboard.writeText(text)
    return true
  } catch {
    const textarea = document.createElement('textarea')

    textarea.value = text
    textarea.setAttribute('readonly', '')
    textarea.style.position = 'fixed'
    textarea.style.left = '-9999px'
    document.body.appendChild(textarea)
    textarea.select()

    const copied = document.execCommand('copy')
    textarea.remove()

    return copied
  }
}

export function downloadTextFile(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')

  link.href = url
  link.download = filename
  link.click()

  URL.revokeObjectURL(url)
}