import type { TripItem, TripState } from './types/trip'

const hotel: TripItem = {
  id: 'hotel-tokyo-station',
  dayIndex: 0,
  name: '东京站附近酒店',
  type: 'hotel',
  timeSlot: 'night',
  address: '1 Chome Marunouchi, Chiyoda City, Tokyo',
  lat: 35.681236,
  lng: 139.767125,
  description: '作为每日出发和返回的住宿点，靠近东京站，适合第一次东京自由行。',
  reason: '交通连接方便，适合作为多日行程的中心点。',
  status: 'confirmed',
  placeId: 'mock-tokyo-station-hotel',
  amapPoiId: 'mock-amap-hotel-tokyo-station',
  mapProvider: 'mock',
  geocodeStatus: 'resolved',
}

export const mockTripState: TripState = {
  destination: '东京',
  dates: ['2026-07-04', '2026-07-05'],
  hotel,
  selectedDayIndex: 1,
  selectedItemId: 'day-1-sensoji',
  preferences: ['经典路线', '美食', '节奏适中'],
  constraints: ['每天 10:00 后开始', '保留弹性时间'],
  days: [
    {
      dayIndex: 1,
      date: '2026-07-04',
      title: '浅草与上野经典路线',
      mainArea: '浅草 / 上野',
      summary: '第一天安排东京东侧经典文化路线，交通移动较少，适合初到东京后进入旅行节奏。',
      items: [
        {
          id: 'day-1-sensoji',
          dayIndex: 1,
          name: '浅草寺',
          type: 'spot',
          timeSlot: 'morning',
          startTime: '10:30',
          endTime: '12:00',
          address: '2 Chome-3-1 Asakusa, Taito City, Tokyo',
          lat: 35.714765,
          lng: 139.796655,
          description: '东京最经典的寺院与浅草街区入口。',
          reason: '第一次去东京的经典文化点，适合作为 Day 1 主线。',
          status: 'planned',
          placeId: 'mock-sensoji',
          amapPoiId: 'mock-amap-sensoji',
          mapProvider: 'mock',
          geocodeStatus: 'resolved',
        },
        {
          id: 'day-1-asakusa-lunch',
          dayIndex: 1,
          name: '浅草周边午餐',
          type: 'restaurant',
          timeSlot: 'lunch',
          startTime: '12:15',
          endTime: '13:15',
          address: 'Asakusa, Taito City, Tokyo',
          lat: 35.711944,
          lng: 139.794722,
          description: '浅草区域内的日式午餐候选点。',
          reason: '减少午餐绕路，保证上午景点和下午路线衔接顺畅。',
          status: 'candidate',
          placeId: 'mock-asakusa-lunch',
          amapPoiId: 'mock-amap-asakusa-lunch',
          mapProvider: 'mock',
          geocodeStatus: 'resolved',
        },
        {
          id: 'day-1-ueno-park',
          dayIndex: 1,
          name: '上野公园',
          type: 'spot',
          timeSlot: 'afternoon',
          startTime: '14:00',
          endTime: '16:30',
          address: 'Uenokoen, Taito City, Tokyo',
          lat: 35.715596,
          lng: 139.77452,
          description: '适合散步、博物馆和轻松下午时段的经典区域。',
          reason: '和浅草同在东京东侧，适合安排在同一天。',
          status: 'planned',
          placeId: 'mock-ueno-park',
          amapPoiId: 'mock-amap-ueno-park',
          mapProvider: 'mock',
          geocodeStatus: 'resolved',
        },
      ],
    },
    {
      dayIndex: 2,
      date: '2026-07-05',
      title: '原宿、表参道与涩谷街区',
      mainArea: '原宿 / 表参道 / 涩谷',
      summary: '第二天集中在东京西侧，兼顾街区漫步、咖啡休息和夜景。',
      items: [
        {
          id: 'day-2-harajuku-station',
          dayIndex: 2,
          name: '原宿站',
          type: 'transport',
          timeSlot: 'morning',
          startTime: '10:30',
          endTime: '10:45',
          address: '1 Chome Jingumae, Shibuya City, Tokyo',
          lat: 35.670168,
          lng: 139.702687,
          description: '当天西侧路线的交通起点。',
          reason: '便于连接原宿、表参道和涩谷区域。',
          status: 'planned',
          placeId: 'mock-harajuku-station',
          amapPoiId: 'mock-amap-harajuku-station',
          mapProvider: 'mock',
          geocodeStatus: 'resolved',
        },
        {
          id: 'day-2-omotesando-cafe',
          dayIndex: 2,
          name: '表参道咖啡休息',
          type: 'cafe',
          timeSlot: 'afternoon',
          startTime: '14:30',
          endTime: '15:30',
          address: 'Omotesando, Minato City, Tokyo',
          lat: 35.665247,
          lng: 139.712314,
          description: '下午节奏调整用的咖啡休息点。',
          reason: '避免连续步行太久，符合适中节奏偏好。',
          status: 'candidate',
          placeId: 'mock-omotesando-cafe',
          amapPoiId: 'mock-amap-omotesando-cafe',
          mapProvider: 'mock',
          geocodeStatus: 'resolved',
        },
        {
          id: 'day-2-shibuya-sky',
          dayIndex: 2,
          name: '涩谷 Sky',
          type: 'activity',
          timeSlot: 'night',
          startTime: '18:00',
          endTime: '19:30',
          address: '2 Chome-24-12 Shibuya, Shibuya City, Tokyo',
          lat: 35.65858,
          lng: 139.701635,
          description: '涩谷夜景与城市观景体验。',
          reason: '适合作为第二天的收尾活动，和当天街区路线顺路。',
          status: 'planned',
          placeId: 'mock-shibuya-sky',
          amapPoiId: 'mock-amap-shibuya-sky',
          mapProvider: 'mock',
          geocodeStatus: 'resolved',
        },
      ],
    },
  ],
}
